[package]
name = "janus_client"
description = "Client for Janus, the server powering ISRG's Divvi Up."
documentation = "https://docs.rs/janus_client"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
backoff = { version = "0.4.0", features = ["tokio"] }
base64 = "0.13.1"
derivative = "2.2.0"
http = "0.2.8"
http-api-problem = "0.55.0"
janus_core = { version = "0.2", path = "../core" }
janus_messages = { version = "0.2", path = "../messages" }
prio = { version = "0.10.0", features = ["multithreaded"] }
rand = "0.8"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls", "json"] }
thiserror = "1.0"
tokio = { version = "1.21", features = ["full"] }
tracing = "0.1.37"
url = "2.3.1"

[dev-dependencies]
assert_matches = "1"
janus_core = { path = "../core", features = ["test-util"]}
mockito = "0.31.0"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter", "fmt"] }
